# Generated by Django 4.1.1 on 2023-02-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_ambientes_edificacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientes',
            name='contribcond',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
