# Generated by Django 4.1.1 on 2023-02-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ambientes_contribcond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambientes',
            name='notaar',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=3),
        ),
    ]
