# Generated by Django 4.1.1 on 2023-02-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_ambientes_notaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacoes',
            name='calcnotacond',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
