# Generated by Django 4.1.1 on 2023-02-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_edificacoes_calcnotacond'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacoes',
            name='notacondgeral',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
    ]
