# Generated by Django 4.1.1 on 2023-02-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_edificacoes_icenv_alter_ambientes_ativ'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacoes',
            name='icmax',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='edificacoes',
            name='icmin',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
