# Generated by Django 4.1.1 on 2023-02-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_edificacoes_notacondgeralcorrigida'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacoes',
            name='notaiccorrigida',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
    ]
