# Generated by Django 4.1.1 on 2023-02-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_edificacoes_notaiccorrigida'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientes',
            name='col1',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ambientes',
            name='col2',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ambientes',
            name='col3',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ambientes',
            name='col4',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
