# Generated by Django 4.1.1 on 2023-02-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_edificacoes_aenv_alter_edificacoes_apcob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacoes',
            name='somacol1',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='edificacoes',
            name='somacol2',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='edificacoes',
            name='somacol3',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='edificacoes',
            name='somacol4',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edificacoes',
            name='aenv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edificacoes',
            name='apcob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edificacoes',
            name='atot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edificacoes',
            name='atotfachada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edificacoes',
            name='fsvidro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edificacoes',
            name='somaabertura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edificacoes',
            name='vtot',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
