# Generated by Django 4.1.1 on 2023-02-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_edificacoes_somacol1_edificacoes_somacol2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacoes',
            name='calcnotail',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='edificacoes',
            name='potilumg',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
