# Generated by Django 4.1.1 on 2023-02-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_edificacoes_somapril1_edificacoes_somapril2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacoes',
            name='notailcorrigida',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
    ]
