# Generated by Django 4.1.1 on 2023-02-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_edificacoes_notailcorrigida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambientes',
            name='pril3',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=55),
        ),
    ]
