# Generated by Django 4.1.1 on 2023-02-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_ambientes_pril3'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacoes',
            name='actotal',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='edificacoes',
            name='autotal',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
