# Generated by Django 4.1.1 on 2023-02-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_edificacoes_actotal_edificacoes_autotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacoes',
            name='notageral',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
    ]
