# Generated by Django 4.1.1 on 2023-02-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_edificacoes_notageral'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacoes',
            name='sg1',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=3),
        ),
        migrations.AddField(
            model_name='edificacoes',
            name='sg2',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=3),
        ),
        migrations.AddField(
            model_name='edificacoes',
            name='sg3',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=3),
        ),
        migrations.AddField(
            model_name='edificacoes',
            name='sg4',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=3),
        ),
        migrations.AddField(
            model_name='edificacoes',
            name='sg5',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=3),
        ),
        migrations.AddField(
            model_name='edificacoes',
            name='sg6',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=3),
        ),
        migrations.AlterField(
            model_name='ambientes',
            name='pril1',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=3),
        ),
        migrations.AlterField(
            model_name='ambientes',
            name='pril2',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=3),
        ),
        migrations.AlterField(
            model_name='ambientes',
            name='pril3',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=3),
        ),
    ]
