# Generated by Django 4.1.1 on 2023-02-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_edificacoes_sg1_edificacoes_sg2_edificacoes_sg3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientes',
            name='areaabertura',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ambientes',
            name='led',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=3),
        ),
    ]
