# Generated by Django 4.1.1 on 2023-03-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_edificacoes_nomepre_alter_ambientes_areaabertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacoes',
            name='term',
            field=models.CharField(blank=True, choices=[('NÃO', 'NÃO'), ('SIM', 'SIM')], max_length=3),
        ),
    ]
