# Generated by Django 4.1.1 on 2023-03-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_edificacoes_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacoes',
            name='prespil1',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='edificacoes',
            name='prespil2',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='edificacoes',
            name='prespil3',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], editable=False, max_length=3),
        ),
    ]
