# Generated by Django 4.1.1 on 2023-03-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_edificacoes_prespil1_edificacoes_prespil2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificacoes',
            name='prespil1',
            field=models.CharField(blank=True, editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='edificacoes',
            name='prespil2',
            field=models.CharField(blank=True, editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='edificacoes',
            name='prespil3',
            field=models.CharField(blank=True, editable=False, max_length=3),
        ),
    ]
