# Generated by Django 4.1.1 on 2023-03-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_edificacoes_prespil1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacoes',
            name='prenv1',
            field=models.CharField(blank=True, editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='edificacoes',
            name='prenv2',
            field=models.CharField(blank=True, editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='edificacoes',
            name='prenv3',
            field=models.CharField(blank=True, editable=False, max_length=3),
        ),
    ]
