# Generated by Django 4.1.1 on 2023-03-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_edificacoes_prenv1_edificacoes_prenv2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacoes',
            name='valornotageral',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
