# Generated by Django 4.1.1 on 2023-03-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_edificacoes_valornotageral'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacoes',
            name='contcond',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='edificacoes',
            name='contenv',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='edificacoes',
            name='contil',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
