# Generated by Django 4.1.1 on 2023-03-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_edificacoes_contcond_edificacoes_contenv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacoes',
            name='somasg',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
