# Generated by Django 4.1.1 on 2023-03-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_edificacoes_somasg'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacoes',
            name='somareq',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
