# Generated by Django 4.1.1 on 2023-03-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_edificacoes_somareq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificacoes',
            name='prcond',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=3),
        ),
        migrations.AlterField(
            model_name='edificacoes',
            name='prgeral',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=3),
        ),
    ]
